# Generated by Django 5.1.4 on 2025-01-10 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_cartitem_order_orderitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
